build.sh

Here's the result from running `build.sh` in Terminal.
```
$ ./build.sh
Building documentation with Lucee :)
Building complete
./build.sh: line 16: [: ==: unary operator expected
```
By putting quotes around the variables, comparison operator can work correctly even when those variables are null.

fixed a shell error [: ==: unary operator expected

---

docs/03.reference/04.additional/chapter.md

Tag implementation is the same as ACF

Remove cfmodule as specific to Lucee

---

builders/html/assets/css/base.css

to make long lines wrap correctly.
[BEFORE](http://docs.lucee.org/guides/lucee-5/component-static.html)
AFTER
Optionally, we can use `<pre><code>` combination as `<code>` already has `white-space: pre-wrap` applied. But the inherited border should be removed by adding `border: none;` to `pre code {...}` block ([line 5878](https://github.com/myleslee/lucee-docs/blob/b16cfb5cad4ccbcdafce0ee71e1848ab3b7f63a1/builders/html/assets/css/base.css#L5878)): 
===============
If you don't want it to wrap, make it scroll with the following addition to `pre` ([line 5870](https://github.com/myleslee/lucee-docs/blob/b16cfb5cad4ccbcdafce0ee71e1848ab3b7f63a1/builders/html/assets/css/base.css#L5870)). Your choice. :) 
```
overflow-x: scroll;
overflow-y: hidden;
```

fix(css): add "white-space: pre-wrap" to PRE tag to make lines wrap correctly

---

docs/04.guides/08.lucee-5/10.lambda/page.md

Lambda functions use `=>` instead of `->` as of 5.0.0.156

updated lambda function syntax

---

docs/03.reference/02.tags/timer/_attributes/type.md

Did some thorough testing on Lucee to more clearly explain how the different timer types will render output.

Fix formatting issue and improve accuracy

---

docs/04.guides/08.lucee-5/15.upgrading-lucee-45/page.md

I read the instruction initially, but missed the part about removing all the other jars (my fault).  Since it is an important step it might be better to have it on it's own line.  There are 4 steps total.

Move instruction to remove all other JARs to its own bullet

---

docs/03.reference/01.functions/hmac/_arguments/encoding.md

Added the encoding options from CFDocs
Gist:
http://trycf.com/gist/01603b838430f8796383c8954ab92dc1/lucee?theme=monokai
This was supposed to be included in an earlier commit.

Added encoding options

---

build.sh

When I was building this project on my laptop, I ran across an error:
```bash
./build.sh: line 21: [: =: unary operator expected
```
I came across this Stack Overflow article that mentioned a fix: http://stackoverflow.com/questions/13617843/unary-operator-expected/13618376
I'm not sure if this will break the deployment and Travis test workflow at all.

Fix unary operator expected error on Mac

---

api/rendering/SyntaxHighlighter.cfc

I broke the build recently because I tried to use a syntax highlighter language of `cfml`. From what I can tell, the Lucee Docs only support `cfm` or `cfs` language syntaxes, so this update will ensure that the language passed to the highlight parser is one of those two syntaxes.

Ensure we only render one of two highlighter languages

---

docs/04.guides/03.updating-lucee/04.migrate-from-acf/page.md

I found this today trying out Lucee -- my application has the above code the application.cfc, so I encountered it immediately.  I couldn't find anything on Google about why the choice was made to be different, but I think it's worth having on this page.

return type difference

---

docs/04.guides/03.updating-lucee/04.migrate-from-acf/page.md

update to note difference in hash() function with iterations (also noted here https://cfdocs.org/hash)

update migrate from ACF page

---

docs/04.guides/02.running-lucee/02.windows/03.installing-apache-tomcat-on-windows/page.md

The application named `ROOT` is invoked when the root of the host is called, casing is important.

ROOT is a name

---

docs/04.guides/02.running-lucee/02.windows/12.configuring-tomcat-as-a-windows-service/page.md

When there are multiple tomcat installations present on one machine information for the default instance is shown. It's therefore good practice to prvide the name of the service on the command line.

provide service name

---

docs/03.reference/01.functions/xmlvalidate/_examples.md

The validator returned an error in the XML document ([Fatal Error] :12:17: XML document structures must start and end within the same entity), but the XML document looks OK to me and passed the validator at www.w3.org.

Update _examples.md for XmlValidate()

---

docs/03.reference/01.functions/writeoutput/_examples.md

I didn't include an example with the ``` encodeFor ``` parameter, because Lucee 4.5.4.017 seems to have a problem with it.

Updated _examples.md for WriteOutput()

---

docs/03.reference/01.functions/arraysort/_examples.md

Code showing the closure example was malformed a bit and not showing up on the docs.

Corrected _examples.md for ArraySort()

---

docs/03.reference/01.functions/cjustify/_examples.md

I added the example usage, but nothing I specify in the second parameter seems to have any effect. I'll be noting this method to be looked at in the source to see whether a bug report needs to be created.

Updated _examples.md for CJustify()

---

docs/03.reference/01.functions/componentcachelist/_examples.md

This might expose pathing information that could be a security concern (unless the luceescript+trycf is *really* sandboxed), so feel free to remove the example, if necessary.

Updated _examples.md for ComponentCacheList()

---

docs/03.reference/01.functions/componentinfo/_examples.md

I know it's deprecated, but it can't hurt to have an example just in case.

Updated _examples.md for ComponentInfo()

---

docs/03.reference/01.functions/dateadd/_examples.md

with `now()` as the second param, it gives wrong results.

fixed param's position

---

api/build/Logger.cfc
api/reference/TagReferenceReader.cfc
server/Application.cfc

// nice for command line building with curl i.e.
curl --trace http://localhost:4040/build_docs/import/?textonly=true
```PS C:\www\lucee-docs> C:\commandBox\curl -trace http://localhost:4040/build_docs/import/?textlogs=true
Lucee Documentation Builder - 5.2.6.60
Importing References (tags, functions, options, methods)
73ms INFO Start Importing new tags and functions
1,531ms INFO 0 functions imported
3,522ms INFO 0 tags imported
3,552ms INFO 0 objects imported
3,816ms INFO 0 methods imported
3,817ms INFO Finished importing new tags and functions
```
use silent to suppress whitespace from getTagData
https://luceeserver.atlassian.net/browse/LDEV-1796

add text mode build logging

---

api/parsers/MarkdownParser.cfc
api/parsers/YamlParser.cfc
build.cfm
import.cfm
server/Application.cfc

enable parallel for all builds, use 4 threads
- add exclusive locks around pegdown and snakeYaml
- snakeYaml only rarely has concurrency issues in testing
LD-109

add locks around non thread safe parsers

---

docs/03.reference/05.objects/struct/filter/_arguments/filter.md

Looks like this was copied from structFilter which needs the struct to filter as a first argument. The member function obviously does not.

Filter argument not used in member function

---

docs/03.reference/05.objects/struct/reduce/_arguments/struct.md

the struct.reduce() member function does not require a struct as an argument

Remove struct argument from struct.reduce()

---

docs/03.reference/01.functions/gettickcount/function.md

The old description of this function seems misleading or outdated. New description reflects the underlying implementation (https://github.com/lucee/Lucee/blob/master/core/src/main/java/lucee/runtime/functions/other/GetTickCount.java) which uses System.currentTimeMillis() or System.nanoTime().

Update description of getTickCount()

---

docs/03.reference/05.objects/array/each/_examples.md

There were no examples for array.each() (unless you knew to look at the
ArrayEach() docs). This commit moves the examples to their correct
locations so they're easier to find.

Improve array.each() and ArrayEach() Examples

---

docs/04.guides/04.cookbooks/12.filesystem-mapping/01.filesystem-mapping-define-mapping/page.md

<cfinclude> should be &lt;cfinclude&gt; .  The following HTML is how it's presented at https://docs.lucee.org/guides/cookbooks/filesystem-mapping/filesystem-mapping-define-mapping.html
<cfinclude> does not work with a full path. This is supported with all filesystems Lucee supports (local,ftp,http,ram,zip,s3 ...).</cfinclude>

HTML entities needed for <cfinclude>.

---

docs/04.guides/01.getting-started/06.commandbox/chapter.md

Fix broken links to Commandbox docs on this page: https://docs.lucee.org/guides/getting-started/commandbox.html

Update Commandbox documentation URLs

---

docs/03.reference/02.tags/application/_attributes/sessioncookie.md

This is very much needed IMHO, the only documentation for how to use this.sessioncookie is at `https://cfdocs.org/application-cfc`.
Full disclosure, I copied these docs straight from that link. ^^ https://cfdocs.org/application-cfc

Add docs for sessioncookie settings in application.cfc

---

docs/04.guides/02.installing-lucee/02.windows/01.installing-and-configuring-lucee-jar-file-on-windows/page.md

I fixed the Lucee Download URL to point to https://download.lucee.org, and I tweaked the verbiage to read better.

Update Lucee Download URL, grammar tweaks

---

docs/04.guides/04.cookbooks/36.s3_sourceCode/page.md

the Lucee application setting for the AWS secret key is `awsSecretKey`, not `secretKey`

AWS Secret Key Variable Incorrect

---

docs/03.reference/05.objects/datetime/diff/_arguments/date2.md

Delete date2 argument for the `date.diff()` member function. It isn't a valid argument.

Update date.diff() member function.

---

docs/03.reference/02.tags/execute/_attributes/terminateOnTimeout.md

I'm not a Java dev, but if I'm reading this right, the default is false - yes?
https://github.com/lucee/Lucee/blob/29b153fc4e126e5edb97da937f2ee2e231b87593/core/src/main/java/lucee/runtime/tag/Execute.java#L72

Document `terminateontimeout` default value for cfexecute

---

docs/04.guides/08.lucee-5/01.extensions/page.md

I replaced 26 code examples in [Extensions in Lucee 5](https://docs.lucee.org/guides/lucee-5/extensions.html) which had backticks messed up.
From this: `â€œinitâ€?` to `init`

Fix invalid backtick characters in Lucee Extension docs

---

docs/04.guides/01.getting-started/07.lucee-editors-IDEs/page.md

I think it's better to promote the [CFML extension](https://marketplace.visualstudio.com/items?itemName=KamasamaK.vscode-cfml) than the [coldfusion extension](https://marketplace.visualstudio.com/items?itemName=ilich8086.ColdFusion) simply because the former is more up to date.
Perhaps I am wrong, and we should simply list the two side-by-side?

Replace Ilich VS Code extension with KamasamaK

---

docs/03.reference/01.functions/getapplicationmetadata/_examples.md

This output also exposes some paths for the website that might be better left hidden, so, if you feel that this example should be removed, please feel free.

Updated _examples.md for getApplicationMetaData()

---

docs/03.reference/01.functions/getdirectoryfrompath/_examples.md

I was going to use `getCurrentTemplatePath()`, but I felt that that would expose too much of the underlying site structure to malicious-minded users.

Updated getDirectoryFromPath() example

---

docs/03.reference/02.tags/queryparam/_examples.md

Without the `luceescript`, it does not render as a code block

Fix example rendering

---

builders/html/layouts/main.cfm

many sites (slack, discord onebox etc) can't handle the escaped <cfcontent> and strip out the tag name from previews. 
with this change, the normal html title stays the same, only the meta title tags are stripped
i.e. this is how the cfcontent page previously shows up on dev.lucee.org

strip out tags from tag page titles

---

docs/03.reference/02.tags/rethrow/tag.md

The cfcatch.tagContext mention was borked in this documentation, so I fixed it. :)

Fixed cfrethrow tagContext mention

---

docs/04.guides/13.Various/27.dev-enviorment/page.md
docs/04.guides/14.Lucee5.3-kabang/page.md

Remove single whitespace character.

Highlight commands and paths for easier reading by using backticks.

---

api/data/FunctionPage.cfc
api/data/MethodPage.cfc
api/data/ObjectPage.cfc
api/data/TagPage.cfc

render them italics, rather than nesting within [], with a tooltip of optional

improve rendering of optional arguments

---

docs/03.reference/02.tags/application/_attributes/ormsettings.md

There is no information at the documentation says Lucee doesn't support the ORM setting autogenmap=false yet. However, the server returns a message that says autogenmap=false is not supported yet.

Lucee doesn't support autogenmap=false yet

---

docs/04.guides/02.installing-lucee/05.installation-linux/03.installation-on-centOS-linux/page.md

I followed the examples from Apache here:
https://httpd.apache.org/docs/2.4/mod/core.html#location

Fix spelling and host config example

---

docs/03.reference/05.objects/struct/each/_arguments/closure.md

It didn't explicitly indicate that the value could be passed into the closure (nor does the example). Now it does.

Update closure for struct.each()

---

docs/04.guides/02.installing-lucee/02.windows/13.installing-lucee-on-windows-2019-with-installer-quick-video-guide/page.md
docs/04.guides/02.installing-lucee/02.windows/chapter.md

Added this Video Guide I've created about installing Lucee on Windows Server 2019 with the installer. I've posted them in lucees support forum first here to help the community https://dev.lucee.org/t/how-to-install-lucee-on-windows-2019-server-iis-video-tutorial/7050 However, the docs is the correct place for them to be. Please feel free to edit, correct, relocate as wished.

Added Windows Server 2019 Installer Video Guide

---

docs/03.reference/02.tags/listing.md

The existing example does not work.

Fix example of overriding tag properties in cflog

---

docs/04.guides/13.Various/15.FAQs/01.technical-FAQs/02.database-session/page.md

Added a mysql structure export of the cf_client_data and cf_session_data for reference, because that has been missed before ( please see https://dev.lucee.org/t/index-on-lucee-client-variables-in-mysql/941/3 ) Please feel free to edit, correct or delete if needed.

Added mysql structure export for reference

---

docs/04.guides/02.installing-lucee/chapter.md

Updated documentation from Oracle JRE to AdoptOpenJDK, because the information was outdated. Didn't add version of JDK, because that would need constant doc update on any installer java upgrade.

Update Java JDK information for installer documentation

---

docs/04.guides/02.installing-lucee/05.installation-linux/07.linux-ubuntu-quick-video-guide/page.md

Got rid of the prefix Quick Video Guide for better search engine indexing, as suggested by Zac

Updated title of lucee install on ubuntu video guide

---

docs/03.reference/05.objects/string/findoneof/_examples.md

Updated the example to use the member method instead of FindOneOf() standalone.

Updated _examples.md for String.findOneOf()

---

api/data/PageReader.cfc
builders/html/helpers/sourceRepoLink.cfm
builders/html/templates/_method.cfm
builders/html/templates/function.cfm
builders/html/templates/tag.cfm

- on linux / CI the file system is case sensitive and the args and attributes filenames weren't being match
- show original Lucee provided args and attribute descriptions in edit mode, when they differ to docs
https://luceeserver.atlassian.net/browse/LDEV-3252

Show local changes and avoid case problems for files LDEV-3252

---

docs/04.guides/13.Various/01.system-properties/page.md

This patch fixes table responsiveness on mobile view for the section "system properties". The markdown tables were breaking the mobile view because they were expanding the complete body/view witdth of the page with unwished results for smaller view widths. This fix contains the former markdown tables now as plain html, because actually it's not possible to wrap markdown tables inside html tags, such as e.g.
<div class="table-responsive">
|  Use as 	|   Notation Example	|
|---	|---	|
|     Environment Variables	| `LUCEE_FULL_NULL_SUPPORT=true` *(MACRO_CASE)*	|
</div>
Known workarounds such as using the 'markdown="1"' attribute on html tags or wrapping inside span tags don't work.

fix table responsiveness on mobile view

---

docs/04.guides/13.Various/01.system-properties/page.md

This patch adds various default values to Environment Variables/System Properties section, adds some information to the descriptions and removes the value 'none' that doesn't exist for LUCEE_LISTENER_MODE

add various default values and fix descriptions

---

docs/04.guides/04.cookbooks/22.Extension-Installation/page.md

I think I was able to correct the image links. What was causing the images not loading was the missing preceding single slash, that makes the browser request load from the root. Without the slash the image gets requested from https://docs.lucee.org/guides/cookbooks/assets/images/screenImages/Extension.png, but the image is located at https://docs.lucee.org/assets/images/screenImages/Extension.png.  This can be seen from Chromes Dev Tool in the network tab and the path column. Don't know why the path is correct when running in Win locally 127.0.0.1:4040

Update page.md to correct image loading

---

docs/04.guides/02.installing-lucee/05.installation-linux/08.linux-install-ubuntu-commandbox/page.md

Codeblocks inbetween of numbered lists/sections break the counting because they always reset numbers to 1. This patch corrects this behaviour by adding the numbers as HTML for the respective lists.

fix Lucee installation guide on ubuntu with commandbox

---

docs/04.guides/13.Various/01.system-properties/page.md

add  LUCEE_LOG_REFLECTION to environment variables and correct LUCEE_MAPPING_FIRST section for better output because of `<pre lang="script">`  identation being outputted.

add LUCEE_LOG_REFLECTION to environment variables

---

docs/03.reference/02.tags/wddx/_examples.md

It took us a while to figure this one out so to save the next dev some  time, an example will do just fine.

Add missing cfscript example for cfwddx

---

docs/03.reference/05.objects/string/encodeforsql/_method.md

As mentioned in LDEV-3540, the `encodeForSQL()` method is not a safe alternative to using query parameters. This PR adds a note that the developer should consider using query parameters instead of this weaker "solution".
https://luceeserver.atlassian.net/browse/LDEV-3540

Add security warning to `encodeForSQL()` docs

---

docs/03.reference/01.functions/getapplicationsettings/function.md

It`s the default as per the detailed attribute doc. https://github.com/lucee/lucee-docs/blob/master/docs/03.reference/02.tags/application/_attributes/scriptProtect.md

Update default of scriptProtect from "none" to "all"

---

docs/04.guides/04.cookbooks/01.application-context-basic/page.md

CFML developers migrating from classic application.cfm to Application.cfc are still experiencing problems to get default templates as a starting point. Most of the resources you can find in the internet are tag based. This should help users to find, copy/create a new Application.cfc easier.

add Application.cfc default template

---

docs/00.home/homepage.md

Update the link anchor text of the Lucee YouTube Link, because on smaller devices the URL as anchor link text wont't fully wrap and force the top navigation header to expand to its full with: the result is parts of the navigation header being pushed out of devices view to the right, hiding for example the search box  icon.

Update the link anchor text

---

Application.cfc
builders/html/assets/Gruntfile.js
builders/html/assets/css/base.35.min.css
builders/html/assets/css/base.css
builders/html/assets/css/base.min.css
builders/html/assets/js/dist/base.35.min.js
docs/03.reference/01.functions/cleartimezone/function.md
server/Application.cfc

This css fixes  the ugly code breaking in `<pre>` tags that wraps code examples by making the pre tag horizontally scrollable. See the red rectangle vs the green rectangle in the image below.
This fix also adds a css cursor: pointer to the search result when the result box gets populated with results.
Please merge with care, because I'm still not that most experienced with the bundling of the assets. However, it worked good on my local dev environment.
.

fix css for correcting long line code breaks in pre-tags

---

docs/04.guides/02.installing-lucee/02.windows/14.installing-lucee-with-xampp-apache2-and-mariadb-on-windows/page.md
docs/04.guides/02.installing-lucee/02.windows/chapter.md

This PR adds a new installing guide that might help PHP developers familiar with XAMPP to try CFML running Lucee locally for development on Windows machines. This configuration should also work on MacOS using Lucee Express, but I couldn't test it because I'm not a MacOs user.

Add "Installing Lucee And XAMPP (Apache2 & MariaDB) on Windows"

---

docs/04.guides/12.deploying-lucee-server-apps/06.preparing-your-server-linux/page.md
docs/04.guides/13.Various/26.server2008-IIS7.5/page.md

It doesn't look like it from the plain-text representation,
But the previous version were displaying the HYPHENS as weird unicode characters.

Correct dody encoding of HYPHEN

---

build.sh
docs/04.guides/13.Various/30.TIPS/05.TIPS-builtIn-Tag/page.md

Also in `docs/04.guides/13.Various/30.TIPS/05.TIPS-builtIn-Tag/page.md` the three blog post links are broken.
Seems `http://www.lucee.ch` is down.
I did a search for `http://www.lucee.ch` in the codebase:

Fix word case and style

---

docs/04.guides/05.working-with-source/01.build-from-source/page.md

The typos are about caps, but the seeming mistake is the reference to Maven where it seems Ant should be named.

Correct seeming mistake and minor typos

---

docs/04.guides/02.installing-lucee/01.download-and-install/page.md

As promised in https://dev.lucee.org/t/lucee-5-3-9-vs-5-3-10/12327/11?u=andreas

Add version numbering  to the download and installing docs

---

.github/workflows/main.yml

When you update or sync your fork and then push to origin on GitHub the publish workflow fails.
Failed actions run seen here:
https://github.com/jbampton/lucee-docs/actions/runs/5434604399/jobs/9883140978
This is from missing secrets.  Also this will stop the extra  workflow failure email that is sent out after you push to your fork

Stop forks from trying to publish the docs

---

docs/03.reference/01.functions/filewriteline/_examples.md

Fixed typo in the documentation example of the function fileWriteLine

fixed typo in documentation: example for function "fileWriteLine" has syntax error.

---

docs/04.guides/13.Various/01.system-properties/page.md

incorrect spelling:
`lucee.extension.install `
correct spelling
`lucee.extensions.install`
see https://github.com/lucee/Lucee/blob/d5c7aec9fbae99ae9d0adac210ab89da6d01b18b/core/src/main/java/resource/setting/sysprop-envvar.json

typo in Update page.md

---

docs/04.guides/02.installing-lucee/03.osx/chapter.md

The previous version was missing a couple of important alternatives. (I could not find better "guides" for those alternatives, here in the docs. So I offered the only suitable resource links I I could find. Is there in fact a "guide" for running the Express edition, or for he docker images?) 
Also tweaked some grammar/typos.

Update guide to install options on Mac

---

docs/04.guides/04.cookbooks/20.query-of-queries/page.md

Issue
The documentation contains an error in the description of filtering people by age. The current text incorrectly states that the filter is for people "under 18 and over 90," which contradicts the actual query logic.
Fix
Correct the description to accurately reflect the query logic, which filters out people "under 90 and over 18."
Changes Made
Updated the description to correctly state the age filtering criteria.
Say you want to filter out people under 18 and over 90, but you don't want to hit the database again:
```lucee
<cfquery name="filteredQuery" dbtype="query">
SELECT     Name, Age, Location
FROM    myQuery
WHERE    Age >= 18
AND Age <= 90
</cfquery>
```
`filteredQry` contains the desired records.
Say you want to filter out people under 90 and over 18, but you don't want to hit …

fix(docs): correct age filtering description

---

builders/html/templates/category.cfm
docs/04.guides/02.installing-lucee/10.lucee-server-adminstration-windows/08.Configuring-SES-url-on-windows/page.md
docs/04.guides/04.cookbooks/24.Query-Handling/page.md
docs/05.categories/090.esapi/category.md
docs/recipes/ai-for-documentation.md
docs/recipes/ai.md
docs/recipes/breaking-changes-6-1.md
docs/recipes/configuration-lucee5.md
docs/recipes/configuration.md
docs/recipes/index.json
docs/recipes/overwrite-build-in-functions-tags.md
docs/recipes/query-handling.md

(mainly, list functions before member functions)

use a better sort order for sub categories

---

docs/03.reference/01.functions/restinitapplication/_arguments/dirPath.md
docs/03.reference/02.tags/dbinfo/_usageNotes.md
docs/03.reference/02.tags/pdf/_attributes/action.md
docs/03.reference/02.tags/pdf/tag.md
docs/04.guides/04.cookbooks/02.application-context-set-mapping/page.md
docs/04.guides/11.developing-with-lucee-server/03.operators/page.md
docs/04.guides/12.deploying-lucee-server-apps/page.md
docs/recipes/breaking-changes-6-2.md
docs/recipes/cfschedule-bulk-update.md
docs/recipes/hooks-and-monitors.md
docs/recipes/query-result-threshold.md
docs/recipes/thread-dump-startup.md
docs/technical-specs/hooks.yaml
docs/technical-specs/monitors.yaml

https://luceeserver.atlassian.net/browse/LDEV-5819

Updated the description and action attribute to include action=extractimage in <cfpdf>

---

docs/04.guides/02.installing-lucee/05.installation-linux/05.installing-in-unattended-mode/page.md

- Update unattended install docs with current options from installer help

Update unattended install docs with current options from installer help
