lucee/lucee-docs

- docs/03.reference/02.tags/exit/_attributes/method.md
The lines currently run together - I've also turned it into a bulleted list with bold text for the values.
> updated formatting on the method attribute values for the exit tag.

- docs/03.reference/02.tags/abort/_attributes/type.md
simplified the description and moved the allowed values to a bulleted list.
> updated abort type attribute description

- docs/03.reference/01.functions/structnew/_arguments/type.md
- docs/03.reference/01.functions/structnew/_examples.md
- docs/03.reference/01.functions/structnew/function.md
> structNew() update

- docs/03.reference/02.tags/directory/_attributes/action.md
list of values for the action attribute
> add action values

- docs/04.guides/05.working-with-source/01.build-from-source/page.md
Attempting to fix a layout issue with page where it has somehow created two columns.
> Attempt to fix layout issue with page

- docs/04.guides/05.working-with-source/01.build-from-source/page.md
Removing erogenous characters and formatting ANT_OPTS correctly
> Erogenous characters and formatting

- .gitignore
- docs/03.reference/01.functions/queryevery/_examples.md
- docs/03.reference/01.functions/queryfilter/_examples.md
- docs/03.reference/01.functions/querymap/_examples.md
- docs/03.reference/01.functions/queryreduce/_examples.md
- docs/03.reference/01.functions/queryslice/_examples.md
- docs/03.reference/01.functions/querysome/_examples.md
- docs/03.reference/01.functions/querysort/_examples.md
- serve.sh
query member function examples that will run on trycf
> query member function examples that will run on trycf

- docs/03.reference/02.tags/calendar/_attributes/dayNames.md
- docs/03.reference/02.tags/calendar/_attributes/disabled.md
- docs/03.reference/02.tags/calendar/_attributes/enabled.md
- docs/03.reference/02.tags/calendar/_attributes/endRange.md
- docs/03.reference/02.tags/calendar/_attributes/firstDayOfWeek.md
- docs/03.reference/02.tags/calendar/_attributes/height.md
- docs/03.reference/02.tags/calendar/_attributes/mask.md
- docs/03.reference/02.tags/calendar/_attributes/monthNames.md
- docs/03.reference/02.tags/calendar/_attributes/name.md
- docs/03.reference/02.tags/calendar/_attributes/onBlur.md
- docs/03.reference/02.tags/calendar/_attributes/onChange.md
- docs/03.reference/02.tags/calendar/_attributes/onFocus.md
- docs/03.reference/02.tags/calendar/_attributes/selectedDate.md
- docs/03.reference/02.tags/calendar/_attributes/startRange.md
- docs/03.reference/02.tags/calendar/_attributes/style.md
- docs/03.reference/02.tags/calendar/_attributes/tooltip.md
- docs/03.reference/02.tags/calendar/_attributes/visible.md
- docs/03.reference/02.tags/calendar/_attributes/width.md
- docs/03.reference/02.tags/calendar/_examples.md
- docs/03.reference/02.tags/calendar/page.md
- docs/03.reference/02.tags/calendar/tag.md
CFCalendar update. Removing attribute files and adding message about it not being supported in Lucee.
> LD-75 - CFCalendar update. Removing attribute files and adding message

- docs/03.reference/02.tags/stopwatch/_attributes/label.md
- docs/03.reference/02.tags/stopwatch/_attributes/variable.md
- docs/03.reference/02.tags/stopwatch/_examples.md
- docs/03.reference/02.tags/stopwatch/tag.md
Fixing cfstopwatch description and adding example code in both tags and script.
> Fixing cfstopwatch description and adding example code in both tags and script.

- docs/03.reference/02.tags/client/page.md
@DominicWatson Notice a small error with cfclient...
> Changing "cfclint" to "cfclient"

- docs/03.reference/01.functions/arraylast/_examples.md
> added example

- docs/04.guides/08.lucee-5/01.extensions/page.md
> Fixing minor layout issue

- docs/03.reference/01.functions/hmac/_arguments/algorithm.md
Added algorithms from CFDocs
Added encodings from CFDocs
> Addressing LD-70

- docs/04.guides/02.running-lucee/01.download-and-install/page.md
Removing invalid reference to custom install details page that doesn't exist.
> Removing invalid reference

- docs/00.home/homepage.md
Updating homepage for Lucee 5 release.
> Updating homepage

- docs/03.reference/02.tags/application/_attributes/InvokeImplicitAccessor.md
- docs/03.reference/02.tags/application/_attributes/action.md
- docs/03.reference/02.tags/application/_attributes/applicationTimeout.md
- docs/03.reference/02.tags/application/tag.md
I was going to overhaul the entire tag documentation page, but yeesh that's a lot of work.
> <cfapplication> documentation updates

- docs/03.reference/01.functions/arraydelete/_examples.md
- docs/03.reference/01.functions/arraydeleteat/_examples.md
- docs/03.reference/01.functions/arrayevery/_examples.md
- docs/03.reference/01.functions/arrayfilter/_examples.md
- docs/03.reference/01.functions/arrayfind/_examples.md
- docs/03.reference/01.functions/arrayfindall/_examples.md
- docs/03.reference/01.functions/arrayfindallnocase/_examples.md
- docs/03.reference/01.functions/arrayindexexists/_examples.md
- docs/03.reference/01.functions/arrayinsertat/_examples.md
- docs/03.reference/01.functions/arrayisdefined/_examples.md
- docs/03.reference/01.functions/arraylast/_examples.md
- docs/03.reference/01.functions/arraylen/_examples.md
- docs/03.reference/01.functions/arraymap/_examples.md
- docs/03.reference/01.functions/arraymid/_examples.md
- docs/03.reference/01.functions/arrayprepend/_examples.md
- docs/03.reference/01.functions/arrayresize/_examples.md
- docs/03.reference/01.functions/arrayslice/_examples.md
Fixed spacing issues causing the markdown parser to parse incorrectly also added a few examples i missed in the first commit
> Fixed markdown spacing issue

- docs/04.guides/08.lucee-5/15.upgrading-lucee-45/page.md
- use full lucee.jar file name
- hyperlink URL
- remove incorrect `etc` from JAR path
- add example commands and paths
> Clarify upgrade instructions

- docs/03.reference/01.functions/listremoveduplicates/_examples.md
add example for listremoveduplicates function
> add example

- docs/04.guides/04.cookbooks/01.application-context-basic/page.md
Session scope is 1st argument, like ACF
> onSessionEnd arguments backwards

- docs/03.reference/01.functions/each/_examples.md
Execute the square root function for every given number.
> Basic each example

- docs/04.guides/01.getting-started/02.newbie-questions/page.md
First pull request (nothing dangerous) updated spelling and punctuation in newbie questions page.
> Lucy -> Lucee

- docs/04.guides/02.running-lucee/02.windows/02.installing-the-boncode-connector-and-mod_cfml/page.md
Instructions on how to download and install and perform basic configuration of Boncode AJP connector and mod_cfml for use with IIS
> Update Windows Boncode docs

- docs/04.guides/05.working-with-source/01.build-from-source/page.md
Included ANT build options as detailed in this discussion:
https://groups.google.com/forum/#!searchin/lucee/build|sort:relevance/lucee/CM15COstv5Q/Di_7w3zCAAAJ
Particularly useful to build without the test cases as I can't get any branch to build successfully when the test cases are included.
I was unable to preview the changes as the preview in the editor on GitHub is not working for me...
> Include ANT build options

- docs/03.reference/01.functions/dateadd/_examples.md
> dateAdd_example.md

- docs/03.reference/01.functions/dateadd/_examples.md
> _examples.md

- docs/04.guides/08.lucee-5/15.upgrading-lucee-45/page.md
> Adding link to download page

- docs/04.guides/08.lucee-5/15.upgrading-lucee-45/page.md
> Fixing link

- docs/04.guides/08.lucee-5/15.upgrading-lucee-45/page.md
> Second attempt to fix link

- docs/03.reference/01.functions/directorycreate/_examples.md
> Updated _examples.md

- docs/04.guides/08.lucee-5/08.functions-tags/page.md
Crammer Change... My first open source contribution :)
> Crammer Change

- docs/03.reference/01.functions/render/_arguments/string.md
- docs/03.reference/01.functions/render/_examples.md
- docs/03.reference/01.functions/render/function.md
Reverts lucee/lucee-docs#246 Breaking the build and still unresolved work to be done
> Revert "Add Render Function"

- docs/04.guides/03.updating-lucee/01.update/page.md
https://dev.lucee.org/t/update-without-using-admin/2408/5
> Update download page URL

- docs/03.reference/02.tags/loop/_examples.md
Added an example for cfloop.
First commit and pull request ... fingers crossed.
> Added cfloop example

- docs/04.guides/11.developing-with-lucee-server/03.operators/page.md
Fixed incorrect example and added missing example.
> Fixed example

- docs/03.reference/01.functions/createobject/function.md
not sure why the changeset is so big, it was by default
> add createobject to component category

- builders/html/layouts/static.cfm
https://luceeserver.atlassian.net/projects/LD/issues/LD-100
> use absolute paths for 404 page assets

- docs/03.reference/01.functions/round/_examples.md
Added example for the Round() function.
> Added example for Round( )

- docs/03.reference/01.functions/parameterexists/_examples.md
I'm not sure the actual intended usage for this method, but some example syntax might help a future user.
> Update _examples.mid for ParameterExists()

- docs/03.reference/01.functions/xmltransform/_examples.md
It's ugly output, but does the trick.
> Update _examples.md for XmlTransform()

- docs/03.reference/01.functions/xmlelemnew/_examples.md
Just a small XML document building example.
> Update _examples.md for XmlElemNew()

- docs/03.reference/01.functions/xmlformat/_examples.md
Forgot to do this one along with the other Xml methods.
> Updated _examples.md for XmlFormat()

- docs/03.reference/01.functions/arrayisempty/_examples.md
Added example of member function usage.
> Updated _examples.md for ArrayIsEmpty()

- docs/03.reference/01.functions/componentcacheclear/_examples.md
I'm not sure whether this is desirable to be put in the luceescript+trycf functionality, since it will be clearing the component cache every time it is run.  Feel free to edit if that is something that might cause problems with the test engine.
> Updated _examples.md for ComponentCacheClear()

- docs/03.reference/01.functions/collectionreduce/_examples.md
A bit of a simplistic example, but good enough to get the ball rolling.
> Updated _examples.md for CollectionReduce()

- docs/03.reference/01.functions/compress/_examples.md
This is another example that I'm not sure how it will work with the luceescript+trycf system, since I'm writing a couple of files then removing them. If file writes are OK with it, great. Otherwise feel free to edit or remove the example.
> Updated _examples.md for Compress()

- docs/03.reference/01.functions/monthasstring/_examples.md
Was using it today, so I figured it might as well update the docs.
> Updated _examples.md for monthAsString()

- docs/04.guides/05.working-with-source/03.java-using-lucee-in-java/page.md
See change: Fixed non-working links to Lucee javaDoc
> Fixed non-working links to Lucee javaDoc

- docs/03.reference/01.functions/getpagecontext/function.md
> Fixed broken link to javadoc

- docs/06.docs/02.build/chapter.md
- fork the documentation
- windows information
- local editing
> updated build notes

- builders/html/Builder.cfc
- builders/html/layouts/main.cfm
- builders/html/layouts/sideNavTree.cfm
one regex reduced the total static build size from 49mb to 41.3mb!
> eliminate excessive repeated new lines

- api/reference/ReferenceImporter.cfc
- docs/03.reference/05.objects/array/_object.md
- docs/03.reference/05.objects/boolean/_object.md
- docs/03.reference/05.objects/datetime/_object.md
- docs/03.reference/05.objects/image/_object.md
- docs/03.reference/05.objects/locale/_object.md
- docs/03.reference/05.objects/query/_object.md
- docs/03.reference/05.objects/string/_object.md
- docs/03.reference/05.objects/struct/_object.md
- docs/03.reference/05.objects/timezone/_object.md
- docs/03.reference/05.objects/xml/_object.md
- docs/05.categories/225.object/category.md
- server/Application.cfc
I keep forgetting categories are based on the folder names, rather than the page id
> fix object categories

- builders/html/layouts/breadcrumbs.cfm
- builders/html/layouts/sideNavTree.cfm
also for performance and to allow adding markup attributes, render all nav links links directly from doc tree instead of via markup
LD-110
> add SiteNavigationElement markup

- builders/html/assets/js/src/uberCoolLuceeDocsSearch.js
This change should fix the regex that was blowing up.
> Fix input string for search to remove non alphanumeric characters

- build.sh
- builders/html/Builder.cfc
- add last mod date (now coz git doesn't tell us)
- ping google
> add sitemaps lastmod and ping

- builders/html/Builder.cfc
> don't index dictionaries

- api/reference/ReferenceImporter.cfc
- a function to manually reformat out artifacts from the xml formatting (disabled)
- add correctly spelled unimplemented to _isHiddenFeature
LD-114
> Reformat text (disabled)

- README.md
Since there should be a contributors agreement signed as well as a pull request.
> Adding more detail to the contribution process.

- docs/03.reference/01.functions/decodeforhtml/_arguments/string.md
> DecodeForHTML description update

- docs/04.guides/01.getting-started/01.first-steps/page.md
Example shown was vulnerable to SQL injection. I know getting started tutorials aren't supposed to be best practice, but the change I've made is simple enough for a new user to be able to follow.
> Example shown vulnerable to SQL injection

- docs/03.reference/01.functions/arrayevery/_examples.md
The previous example was more suited for ArrayEach() usage.
> Updated _examples.md for ArrayEvery()

- docs/03.reference/01.functions/asin/_examples.md
Updated the example code with Luceescript+TryCF.  This one correctly shows the expected answer in radians.
> Update _examples.md for Asin()

- docs/03.reference/01.functions/yesnoformat/_arguments/value.md
Corrected for better English.  Just the former editor coming out in me.
> Updated value.md

- docs/03.reference/01.functions/arrayeach/_examples.md
> Thread Example - process 3 at a time

- docs/03.reference/01.functions/duplicate/_examples.md
Since there wasn't an existing example., I added a rudimentary one.  I tried to dig around to get a good example of deep copy vs. non-deep copy, but I couldn't really find one that would work here.
> Updated _examples.md for Duplicate()

- docs/03.reference/01.functions/listeach/_examples.md
corrected indentation which causes trycf not working
> corrected indentation

- docs/04.guides/13.Various/32.tutorial-lucee/02.tutorial-java-in-lucee/page.md
Lots of minor grammatical and casing tweaks.
Feel free to reject because it's "unnecessary", but IMHO this looks better and reads better than the old version.
> Java in Lucee - docs update, upper-case first letter

- docs/04.guides/14.Lucee5.3-kabang/page.md
> fix image paths

- docs/04.guides/11.developing-with-lucee-server/01.language-syntax-differences/page.md
Add note about cfproperty not supporting lazy attribute.
> Update language differences doc - cfproperty lazy attribute

- docs/03.reference/05.objects/datetime/diff/_arguments/datepart.md
Update available `datepart` argument values for date.diff() member function.
> Update date.diff() member function.

- builders/html/Builder.cfc
as the docs build is multi-threaded, avoid errors with createDirectory
> add a lock around createDirectory

- docs/03.reference/01.functions/each/function.md
- docs/05.categories/295.thread/category.md
> add Each() to Threads category

- docs/03.reference/01.functions/replace/_arguments/replacement.md
- docs/03.reference/01.functions/replace/_arguments/substring.md
- docs/03.reference/01.functions/replace/_examples.md
- add more examples
- document function argument
> update replace docs

- docs/03.reference/01.functions/serializejson/_arguments/queryFormat.md
- docs/03.reference/01.functions/serializejson/_arguments/useSecureJSONPrefixOrCharset.md
- docs/03.reference/02.tags/application/_attributes/cachedafter.md
- docs/03.reference/02.tags/application/_attributes/proxy.md
- docs/03.reference/02.tags/application/_attributes/psq.md
- docs/03.reference/02.tags/application/_attributes/variableusage.md
- docs/03.reference/02.tags/schedule/_attributes/unique.md
- docs/03.reference/02.tags/zip/_attributes/encryptionalgorithm.md
- docs/03.reference/02.tags/zip/_attributes/password.md
- docs/03.reference/02.tags/zipparam/_attributes/encryptionalgorithm.md
- docs/03.reference/02.tags/zipparam/_attributes/password.md
includes https://github.com/lucee/extension-compress/pull/1
> import new 5.3.2.77 documentation

- docs/03.reference/01.functions/queryfilter/_arguments/filter.md
- docs/03.reference/05.objects/query/filter/_arguments/filter.md
- docs/03.reference/05.objects/query/filter/_examples.md
- docs/04.guides/04.cookbooks/43.QOQ_Sucks/page.md
> Add query performance examples

- docs/04.guides/08.lucee-5/01.extensions/page.md
> Minor fixes and manifest.mk typo

- docs/03.reference/01.functions/queryexecute/_arguments/params.md
Minor edit to queryexecute params
> Minor edit to queryexecute params

- docs/03.reference/02.tags/queryparam/_examples.md
Fixing cfqueryparam example as output was broken.
> Fixing cfqueryparam example

- docs/03.reference/01.functions/queryexecute/_examples.md
Updating queryexecute example with working trycf example
> Updating queryexecute example

- docs/04.guides/13.Various/37.deploy-AWSElasticBeanstalk/page.md
> Update Numbered list in AWS instruction Guide

- docs/04.guides/13.Various/15.FAQs/01.technical-FAQs/02.database-session/page.md
Notes on supported session type and database type.
> Update page.md to add some considerations

- docs/03.reference/01.functions/getauthuser/_examples.md
Added script version to the tag-based example.
> Updated _examples.md for getAuthUser()

- docs/03.reference/01.functions/getfilefrompath/_examples.md
Just bringing it in line with the reset of the documentation.
> Updates the existing example for getFileFromPath()

- docs/03.reference/01.functions/getcontextroot/_examples.md
This doesn't seem to be terribly thrilling, but just getting it in there to make sure there is some usage shown.
> Added code example for getContextRoot()

- docs/03.reference/01.functions/spreadsheetnew/_examples.md
- docs/03.reference/01.functions/spreadsheetnew/page.md
- docs/03.reference/01.functions/spreadsheetsetcellvalue/_examples.md
- docs/03.reference/01.functions/spreadsheetsetcellvalue/page.md
- docs/03.reference/01.functions/spreadsheetwrite/_examples.md
- docs/03.reference/01.functions/spreadsheetwrite/page.md
https://luceeserver.atlassian.net/browse/LD-126
> For LD-126 - spreadsheet functions are not supported

- docs/03.reference/02.tags/form/_attributes/encType.md
- docs/03.reference/02.tags/form/_attributes/preserveData.md
- docs/03.reference/02.tags/form/_attributes/scriptSrc.md
- docs/03.reference/02.tags/form/_attributes/style.md
- docs/03.reference/02.tags/form/tag.md
- docs/03.reference/02.tags/input/tag.md
- docs/03.reference/02.tags/select/tag.md
- docs/03.reference/02.tags/slider/tag.md
- fix unsupprorted message for preservedata
> cross ref cfform tag

- docs/03.reference/01.functions/arraydeleteat/_examples.md
Example of deleteAt uses delete function. Updated to use correct function
> Correct function in example

- docs/04.guides/04.cookbooks/52.Flyingsaucer/page.md
> Syntax fix

- docs/03.reference/02.tags/ldap/_attributes/secure.md
list the options 
https://github.com/lucee/Lucee/blob/5.3/core/src/main/java/lucee/runtime/tag/Ldap.java#L208
> add cfldap secure options

- docs/04.guides/04.cookbooks/32.Startup_Listeners/page.md
Please capitalize Server.cfc in all places. Lucee doesn't pick up the file if it isn't capitalized. Same for Web.cfc
> Startup_Listeners.html

- docs/03.reference/02.tags/function/_attributes/access.md
following up on 
https://github.com/lucee/Lucee/pull/864
> document function access types

- docs/04.guides/03.updating-lucee/02.migrate-from-railo/page.md
- docs/04.guides/04.cookbooks/14.check-for-changes/page.md
- docs/04.guides/07.about-lucee/02.lucee-compared/02.lucee-compared-with-java/page.md
- docs/04.guides/08.lucee-5/chapter.md
When looking at the docs here on GitHub I noticed some markup was broken.
> Fix Markdown headings.

- builders/html/templates/function.cfm
https://github.com/lucee/Lucee/pull/876
> handle typo in lucee source

- docs/03.reference/01.functions/arrayeach/function.md
- docs/03.reference/01.functions/queryeach/function.md
- docs/03.reference/01.functions/structeach/function.md
- docs/03.reference/05.objects/array/each/_method.md
- docs/03.reference/05.objects/query/each/_method.md
- docs/03.reference/05.objects/struct/each/_method.md
- docs/04.guides/11.developing-with-lucee-server/03.operators/page.md
also cross reference each with threads
> add note that ++ and -- aren't thread safe

- builders/html/Builder.cfc
- builders/html/layouts/breadcrumbs.cfm
fixes problem introduced by https://github.com/lucee/lucee-docs/pull/781
> use local hostname for bread crumbs in edit mode

- docs/03.reference/01.functions/deserializejson/_examples.md
for strictmapping false, with nested queries
> added nested deserializeJSON example

- docs/03.reference/01.functions/throw/_arguments/detail.md
- docs/03.reference/01.functions/throw/_arguments/extendedInfo.md
- docs/03.reference/01.functions/throw/_arguments/object.md
- docs/03.reference/01.functions/throw/_examples.md
- docs/03.reference/02.tags/throw/_attributes/extendedInfo.md
- docs/03.reference/02.tags/throw/_attributes/object.md
https://luceeserver.atlassian.net/browse/LDEV-2832
> improve throw documentation

- api/data/MethodPage.cfc
https://luceeserver.atlassian.net/browse/LD-130
> show the correct return type for member functions LD-130

- builders/html/templates/tag.cfm
ref https://luceeserver.atlassian.net/browse/LDEV-231
> display tag attribute aliases

- builders/html/layouts/main.cfm
- builders/html/layouts/static.cfm
Add missing alt attributes to images.
> Remove the XHTML syntax from the meta and link tags.

- docs/06.docs/01.structure/page.md
- docs/06.docs/02.build/chapter.md
> Fix grammar for "whose" not "who's"

- builders/html/layouts/main.cfm
Changing "Mailing List" to "Developer Forum" and adding "Newsletter Signup" with link to MailChimp form.
> Adjusting side nav

- docs/03.reference/02.tags/loop/_attributes/index.md
updating doco to reflect
https://www.bennadel.com/blog/3851-struct-iteration-with-cfloop-exposes-both-key-and-value-in-lucee-cfml-5-3-6-61.htm
https://docs.lucee.org/reference/tags/loop.html#attribute-index
> cfloop over a struct struct with index and item values

- docs/03.reference/02.tags/argument/_attributes/type.md
> format list

- .markdownlint.yml
- README.md
- docs/03.reference/01.functions/parsedatetime/_arguments/format.md
- docs/03.reference/05.objects/datetime/datetimeformat/_arguments/mask.md
- docs/03.reference/05.objects/datetime/lsdatetimeformat/_arguments/mask.md
- docs/04.guides/01.getting-started/01.first-steps/page.md
- docs/04.guides/01.getting-started/02.newbie-questions/page.md
- docs/04.guides/02.installing-lucee/02.windows/02.installing-the-boncode-connector-and-mod_cfml/page.md
- docs/04.guides/02.installing-lucee/02.windows/11.starting-tomcat-and-verifying-the-installation-on-windows/page.md
- docs/04.guides/02.installing-lucee/05.installation-linux/04.upgrade-JRE/page.md
- docs/04.guides/02.installing-lucee/10.lucee-server-adminstration-windows/06.updating-Tomcat-uriworkermap-properties-file/page.md
- docs/04.guides/03.updating-lucee/02.migrate-from-railo/page.md
- docs/04.guides/04.cookbooks/22.Extension-Installation/page.md
- docs/04.guides/05.working-with-source/02.build-4x-from-source/page.md
- docs/04.guides/06.extensions/09.extension-infinispan/page.md
- docs/04.guides/06.extensions/10.extension-membase/page.md
- docs/04.guides/06.extensions/11.extension-mongoDB/page.md
- docs/04.guides/06.extensions/12.extensions-couchdb/page.md
- docs/04.guides/12.deploying-lucee-server-apps/01.securing-lucee-server-apps/page.md
- docs/04.guides/13.Various/04.Amf-configuration/page.md
- docs/04.guides/13.Various/05.command-line-interface/page.md
- docs/04.guides/13.Various/25.server2003-IIS6/page.md
- docs/04.guides/13.Various/30.TIPS/02.TIPS-tricks/page.md
- docs/04.guides/13.Various/32.tutorial-lucee/02.tutorial-java-in-lucee/page.md
- docs/04.guides/13.Various/32.tutorial-lucee/03.tutorial-patch-behind-proxy/page.md
- docs/04.guides/13.Various/37.deploy-AWSElasticBeanstalk/page.md
MD034 - Bare URL used.
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used
> Lint Markdown: fix bare URLs.

- docs/04.guides/13.Various/32.tutorial-lucee/02.tutorial-java-in-lucee/page.md
https://blog.simplicityweb.co.uk/121/loading-java-libraries-dynamically-in-lucee-without-javaloader
for https://docs.lucee.org/guides/Various/tutorial-lucee/tutorial-java-in-lucee.html
> add link about loading java libs

- docs/03.reference/01.functions/gettickcount/_examples.md
https://docs.lucee.org/reference/functions/gettickcount.html
> better getTickCount example

- docs/03.reference/01.functions/valuelist/function.md
https://docs.lucee.org/reference/functions/valuelist.html
> link to valuelist to queryColumnList

- docs/03.reference/01.functions/callstackget/_examples.md
https://docs.lucee.org/reference/functions/callstackget.html
> better CallStackGet example

- Application.cfc
- server/Application.cfc
this speeds up the build process
> use Localmode for docs

- docs/03.reference/02.tags/pdf/_attributes/action.md
https://docs.lucee.org/reference/tags/pdf.html#attribute-action
https://github.com/lucee/extension-pdf/pull/14
> add missing pdf actions

- docs/03.reference/02.tags/zipparam/_attributes/entryPath.md
https://docs.lucee.org/reference/tags/zipparam.html#attribute-entrypath
> format zipparam entrypath

- docs/03.reference/02.tags/zip/_attributes/compressionmethod.md
https://docs.lucee.org/reference/tags/zip.html#attribute-compressionmethod
> formatting

- docs/03.reference/02.tags/ftp/_attributes/action.md
https://docs.lucee.org/reference/tags/ftp.html#attribute-action
> add cfftp actions

- docs/04.guides/11.developing-with-lucee-server/03.operators/page.md
I believe that the previous documentation is both inaccurate and unclear. Adds a more accurate description and lots more examples.
> Update documentation of elvis operator

- docs/03.reference/01.functions/left/_examples.md
https://docs.lucee.org/reference/functions/left.html
> improve left Example

- docs/03.reference/01.functions/compress/_arguments/format.md
https://docs.lucee.org/reference/functions/compress.html#argument-format
> format compression formats

- docs/03.reference/02.tags/thread/tag.md
https://docs.lucee.org/reference/tags/thread.html
> add notes about cfthread extra arguments

- docs/03.reference/01.functions/debugadd/function.md
https://docs.lucee.org/reference/functions/debugadd.html
> add category for DebugAdd

- docs/03.reference/01.functions/querygetrow/function.md
- docs/03.reference/05.objects/query/getrow/_method.md
https://docs.lucee.org/reference/objects/query/getrow.html
https://docs.lucee.org/reference/functions/querygetrow.html
> link queryRowData

- docs/03.reference/01.functions/val/function.md
https://docs.lucee.org/reference/functions/val.html
> cross ref val

- docs/04.guides/02.installing-lucee/05.installation-linux/07.linux-ubuntu-quick-video-guide/page.md
- docs/04.guides/02.installing-lucee/05.installation-linux/chapter.md
- docs/04.guides/02.installing-lucee/chapter.md
Added Video Guide I've created about installing Lucee on a clean Ubuntu 20.04LTS Server with the installer. It consists of 8 step-by-step videos using an GUI X11 SSH Forwarding approach. Please feel free to edit, correct, relocate or deny/reject pull request as wished.
> Added Ubuntu 20.04LTS Server Installer Video Guide

- docs/04.guides/12.deploying-lucee-server-apps/page.md
> add information about deploy and patches folders

- api/sqlitecfc/lib/javaloader/JavaLoader.cfc
- api/sqlitecfc/lib/javaloader/JavaProxy.cfc
> Fix case of ColdFusion and Java

- docs/04.guides/02.installing-lucee/05.installation-linux/07.linux-ubuntu-quick-video-guide/page.md
added missing command snippet 'sudo lsof -i 6' for video step 8 Enhancing Tomcat's And Apache2's Security
> add missing command in ubuntu video guide

- builders/html/layouts/main.cfm
was Lucee Documentation :: Lucee Documentation
now just Lucee Documentation
> improve home title

- docs/03.reference/02.tags/document/_attributes/permissions.md
https://docs.lucee.org/reference/tags/document.html#attribute-permissions
> format cfdocument permissions list

- docs/03.reference/01.functions/nullvalue/_examples.md
In order to add the code example I just put a link in the comment to the Lucee video for null support.
> Updated _examples.md for NullValue()

- api/sqlitecfc/lib/javaloader/JavaLoader.cfc
- docs/00.home/homepage.md
- docs/03.reference/01.functions/createobject/_arguments/classname.md
- docs/03.reference/01.functions/createobject/_arguments/type.md
- docs/03.reference/01.functions/isobject/_examples.md
- docs/03.reference/02.tags/throw/_attributes/object.md
- docs/04.guides/02.installing-lucee/10.lucee-server-adminstration-windows/07.implementing-log-rotation-with-log4j/page.md
- docs/04.guides/04.cookbooks/15.event-gateway/01.create-event-gateway/page.md
- docs/04.guides/04.cookbooks/15.event-gateway/page.md
- docs/04.guides/04.cookbooks/31.Externalize_Strings/page.md
- docs/04.guides/04.cookbooks/34.Types_lucee/page.md
- docs/04.guides/04.cookbooks/54.xmlFast&Easy/page.md
- docs/04.guides/06.extensions/10.extension-membase/page.md
- docs/04.guides/07.about-lucee/02.lucee-compared/02.lucee-compared-with-java/page.md
- docs/04.guides/13.Various/04.Amf-configuration/page.md
- docs/04.guides/13.Various/32.tutorial-lucee/02.tutorial-java-in-lucee/01.using-lucee-in-java/page.md
- docs/04.guides/13.Various/33.ubuntu-lucee-with-Tomcat7-multi-instance/page.md
- docs/04.guides/13.Various/39.cfadmin/page.md
Also fixed the word `documentation`
> Fix case of Java.

- docs/04.guides/04.cookbooks/12.filesystem-mapping/01.filesystem-mapping-define-mapping/page.md
https://docs.lucee.org/guides/cookbooks/filesystem-mapping/filesystem-mapping-define-mapping.html
> add link to blog posts about mappings

- api/data/Page.cfc
- api/data/PageCache.cfc
- docs/03.reference/01.functions/getvfsmetadata/function.md
- docs/03.reference/01.functions/storeaddacl/function.md
- docs/03.reference/01.functions/storegetacl/function.md
- docs/03.reference/01.functions/storegetmetadata/function.md
- docs/03.reference/01.functions/storesetmetadata/function.md
- docs/04.guides/04.cookbooks/26.Vitural-FileSystem/page.md
- docs/04.guides/04.cookbooks/36.s3_sourceCode/page.md
- docs/04.guides/13.Various/21.lucee-resources/page.md
- docs/05.categories/110.files/category.md
- docs/05.categories/293.s3/category.md
also fixed some bugs due to not using setters
> Add S3 category, cross ref

- builders/html/helpers/metaDescription.cfm
This PR fixes the description updates for dynamic page listing, such as created by categories.cfm at https://docs.lucee.org/categories or functions.cfm at https://docs.lucee.org/reference/functions.html
> Fix descriptions for categories and references.

- docs/04.guides/04.cookbooks/52.Flyingsaucer/page.md
https://docs.lucee.org/guides/cookbooks/Flyingsaucer.html
> add note about cfdocument type=modern|classic

- .markdownlint.yml
- docs/03.reference/01.functions/filereadbinary/function.md
- docs/04.guides/02.installing-lucee/05.installation-linux/04.upgrade-JRE/page.md
- docs/04.guides/02.installing-lucee/05.installation-linux/06.changing-the-user-account-lucee-uses/page.md
- docs/04.guides/04.cookbooks/40.System_output/page.md
- docs/04.guides/12.deploying-lucee-server-apps/01.url-rewriting/page.md
- docs/04.guides/13.Various/08.configuration-web-xml/page.md
- docs/04.guides/13.Various/32.tutorial-lucee/02.tutorial-java-in-lucee/01.using-lucee-in-java/page.md
- docs/04.guides/14.Lucee5.3-kabang/page.md
- remove single and 3 or more spaces from end of lines
- set 'br_spaces' to 2 to enable line breaks from lines that end in 2 spaces
> Remove trailing spaces

- docs/04.guides/12.deploying-lucee-server-apps/01.securing-lucee-server-apps/02.lucee-lockdown-guide/page.md
https://docs.lucee.org/guides/deploying-lucee-server-apps/securing-lucee-server-apps/lucee-lockdown-guide.html
> add note about LUCEE_ADMIN_ENABLED

- docs/03.reference/01.functions/structkeyarray/_examples.md
- docs/03.reference/05.objects/struct/keyarray/_examples.md
added ordered examples
https://docs.lucee.org/reference/functions/structkeyarray.html
https://docs.lucee.org/reference/objects/struct/keyarray.html
> improve structKeyArray examples

- docs/03.reference/05.objects/struct/some/_examples.md
https://docs.lucee.org/reference/functions/structsome.html
> add structsome examples

- .markdownlint.yml
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md009---trailing-spaces
> Remove trailing spaces check

- docs/03.reference/01.functions/arraysort/_arguments/locale_sensitive.md
- docs/03.reference/01.functions/arraysort/_arguments/sorttype_or_closure.md
- docs/03.reference/01.functions/querysort/_arguments/columnNameOrSortFunc.md
- docs/03.reference/01.functions/querysort/_arguments/direction.md
- docs/03.reference/01.functions/querysort/_examples.md
- docs/03.reference/05.objects/array/sort/_arguments/locale_sensitive.md
- docs/03.reference/05.objects/array/sort/_arguments/sorttype_or_closure.md
- docs/03.reference/05.objects/query/sort/_arguments/columnNameOrSortFunc.md
- docs/03.reference/05.objects/query/sort/_arguments/direction.md
- docs/03.reference/05.objects/query/sort/_examples.md
https://docs.lucee.org/reference/functions/querysort.html
> add query sort closure examples

- docs/04.guides/13.Various/15.FAQs/01.technical-FAQs/02.database-session/page.md
expires column should be indexed so that purging do get timed out.
> index hint on session tables

- docs/03.reference/01.functions/listtoarray/_arguments/includeEmptyFields.md
https://docs.lucee.org/reference/functions/listtoarray.html
> listtoarray includeEmptyFields state explicit default

- docs/03.reference/01.functions/isclosure/_examples.md
- docs/03.reference/01.functions/isclosure/function.md
https://docs.lucee.org/reference/functions/isclosure.html
> add isclosure example

- docs/03.reference/01.functions/filesetattribute/_arguments/attribute.md
https://docs.lucee.org/reference/functions/filesetattribute.html
> update fileSetAttribute with windows attributes

- docs/03.reference/02.tags/file/_attributes/storeacl.md
Based on test suite code in https://github.com/MitrahSoft/Lucee/blob/master/test/tickets/LDEV1489.cfc
https://docs.lucee.org/reference/tags/file.html#attribute-storeacl
> Improve documentation for possible values of `storeACL`/`acl`

- docs/04.guides/05.working-with-source/01.build-from-source/page.md
as per https://github.com/lucee/Lucee/pull/1218
> document build testFilter

- docs/03.reference/02.tags/application/_attributes/wstype.md
only Axis 1 is actually supported
https://github.com/lucee/extension-axis/blob/master/source/java/src/org/lucee/extension/axis/Axis1Handler.java#L149
> remove webservice CXF option

- docs/04.guides/01.getting-started/03.system-requirements/page.md
Add Windows 2016, 2019 Server editions and remove old OS that reached end of life support
> Update system requirements to actual windows software

- docs/03.reference/01.functions/encodeforxml/_arguments/canonicalize.md
- docs/03.reference/01.functions/xmlformat/function.md
https://dev.lucee.org/t/xmlformat-and-encodeforxml-with-accents-characters/8133
> cross ref xmlformat

- docs/03.reference/02.tags/savecontent/tag.md
add cfsavecontent to core cfml category
> add cfsavecontent to core cfml category

- docs/03.reference/02.tags/abort/tag.md
> add cfabort to core category

- docs/03.reference/02.tags/execute/tag.md
add cfexecute to core cfml category
> add cfexecute to core cfml category

- docs/03.reference/02.tags/file/tag.md
> add cffile to core category

- docs/03.reference/02.tags/directory/tag.md
add cfdirectory to core cfml category
> add cfdirectory to core cfml category

- docs/03.reference/02.tags/header/tag.md
add cfheader to core cfml categories
> add cfheader to core cfml categories

- docs/03.reference/02.tags/elseif/tag.md
add elseif tag to cfml core category
> add elseif tag to cfml core category

- docs/03.reference/02.tags/else/tag.md
add cfelse to core cfml category
> add cfelse to core cfml category

- docs/03.reference/02.tags/application/_attributes/scriptProtect.md
this patch updates the application cfc attribute for this.scriptProtect in the docs
> update this.scriptProtect for application.cfc tag

- docs/04.guides/13.Various/05.command-line-interface/page.md
https://luceeserver.atlassian.net/browse/LD-129
> Changed the invalid URL point to the commandbox

- docs/04.guides/04.cookbooks/15.event-gateway/01.create-event-gateway/page.md
- docs/04.guides/04.cookbooks/15.event-gateway/02.event-gateways-lucee/page.md
- docs/04.guides/04.cookbooks/15.event-gateway/page.md
- docs/04.guides/06.extensions/02.extension-websocket/page.md
- docs/05.categories/130.gateways/category.md
- docs/05.categories/85.event-gateways/category.md
https://docs.lucee.org/categories/gateways.html
> cross reference event gateways

- docs/04.guides/02.installing-lucee/05.installation-linux/08.linux-install-ubuntu-commandbox/page.md
- docs/04.guides/02.installing-lucee/05.installation-linux/chapter.md
- docs/04.guides/02.installing-lucee/chapter.md
2nd try. This PR adds an installation guide using CommandBox on Ubuntu20.04LTS using Apache2 AJP
> add installation guide CommandBox Ubuntu Apache2

- docs/04.guides/05.working-with-source/01.build-from-source/page.md
https://github.com/lucee/Lucee/pull/1320
> add information about multiple test filters to build notes

- api/parsers/MarkdownParser.cfc
- api/rendering/TemplateRenderer.cfc
- builders/html/templates/function.cfm
- builders/html/templates/tag.cfm
builds on https://github.com/lucee/lucee-docs/pull/1141
also add missing deprecated status for tags
> add link for deprecated status

- api/data/FunctionPage.cfc
- api/data/PageReader.cfc
- api/data/TagPage.cfc
- api/reference/ReferenceImporter.cfc
- builders/html/templates/function.cfm
- builders/html/templates/tag.cfm
- docs/03.reference/01.functions/s3copy/_arguments/accessKeyId.md
- docs/03.reference/01.functions/s3copy/_arguments/secretAccessKey.md
- docs/03.reference/01.functions/s3copy/_arguments/srcBucketName.md
- docs/03.reference/01.functions/s3copy/_arguments/srcObjectName.md
- docs/03.reference/01.functions/s3copy/_arguments/timeout.md
- docs/03.reference/01.functions/s3copy/_arguments/trgBucketName.md
- docs/03.reference/01.functions/s3copy/_arguments/trgObjectName.md
- docs/03.reference/01.functions/s3copy/function.md
- docs/03.reference/01.functions/s3move/_arguments/accessKeyId.md
- docs/03.reference/01.functions/s3move/_arguments/secretAccessKey.md
- docs/03.reference/01.functions/s3move/_arguments/srcBucketName.md
- docs/03.reference/01.functions/s3move/_arguments/srcObjectName.md
- docs/03.reference/01.functions/s3move/_arguments/timeout.md
- docs/03.reference/01.functions/s3move/_arguments/trgBucketName.md
- docs/03.reference/01.functions/s3move/_arguments/trgObjectName.md
- docs/03.reference/01.functions/s3move/function.md
- functions have return types and usage notes
- tags have usage notes
- edit links are only shown on the live site when content exists
- otherwise to add content, use the interactive local build
plus all the empty stub files
> add usage notes and return types

- docs/03.reference/01.functions/createobject/_examples.md
- docs/03.reference/01.functions/createobject/function.md
https://docs.lucee.org/reference/functions/createobject.html
> add createObject new object() syntax examples

- api/data/DocTree.cfc
- api/data/Page.cfc
- api/data/PageReader.cfc
- api/reference/FunctionReferenceReader.cfc
- api/reference/MethodReferenceReader.cfc
- api/reference/TagReferenceReader.cfc
- builders/html/templates/_method.cfm
- builders/html/templates/function.cfm
https://luceeserver.atlassian.net/browse/LD-139
> hide hidden arguments and attributes LD-139

- builders/html/templates/function.cfm
- builders/html/templates/tag.cfm
https://luceeserver.atlassian.net/browse/LD-138
> list unimplemented args / attrs seperately LD-138

- docs/03.reference/02.tags/map/_examples.md
- docs/03.reference/02.tags/map/tag.md
- docs/03.reference/02.tags/mapitem/_examples.md
- docs/03.reference/02.tags/mapitem/tag.md
- docs/05.categories/010.ajax/category.md
https://docs.lucee.org/reference/tags/map.html
> add map examples and cross ref

- docs/04.guides/08.lucee-5/13.tags/page.md
Signed-off-by: Charlie Arehart <charlie@carehart.org>
> Add link to additional docs on these mentioned features of cachedwithin

- docs/03.reference/02.tags/savecontent/_examples.md
https://docs.lucee.org/reference/tags/savecontent.html
> add cfsavecontent script example

- docs/04.guides/02.installing-lucee/01.download-and-install/page.md
This PR greatly complements/adds/restructures the exisiting download page and adds important hints and information (without removing already exisiting informations) about installing/running each Lucee flavor in a more comprehensive but compact way for quick reference and understanding all installation/running flavours as a more global, non-OS-dependant perspective. 
From my point of view this is how the starting point of the installation/download documentation should look like in future. Other more detailed and OS dependant instructions (such as installer on Linux or installer on Windows) could be linked and referenced in this section later on. But for now, I think that this is how the starting point should look like. 
Please consider that I'm not native in English, this PR might need …
> add/restructure with important information/hints

- docs/03.reference/01.functions/directorylist/_usageNotes.md
- docs/03.reference/02.tags/directory/_usageNotes.md
https://luceeserver.atlassian.net/browse/LDEV-2118
https://docs.lucee.org/reference/functions/directorylist.html
https://docs.lucee.org/reference/tags/directory.html
> add notes about mode column not being populated

- docs/03.reference/02.tags/application/_attributes/sessioncookie.md
Saw it was still missing in the docs!
> add sameSite directive for application.sessioncookie

- docs/04.guides/13.Various/32.tutorial-lucee/02.tutorial-java-in-lucee/page.md
https://docs.lucee.org/guides/Various/tutorial-lucee/tutorial-java-in-lucee.html
> Add table for datatypes comparison

- docs/04.guides/13.Various/24.rest-services/page.md
This is another heavy update for the docs. This time there is a new step by step configuration guide for REST in Lucee with additional information about serving it behind IIS and Apache2 on Ubuntu/Linux.
> update REST documentation

- docs/03.reference/01.functions/transactionsetsavepoint/_usageNotes.md
http://docs.localhost:81/reference/functions/transactionsetsavepoint.html
https://luceeserver.atlassian.net/browse/LDEV-3657
> add usage note TransactionSetSavePoint and orm

- docs/03.reference/02.tags/savecontent/_examples.md
> remove unused output variable

- docs/03.reference/01.functions/encodeforhtml/_examples.md
- docs/03.reference/01.functions/encodeforhtmlattribute/_examples.md
- docs/03.reference/01.functions/invoke/_examples.md
- docs/03.reference/01.functions/isimage/_examples.md
- docs/03.reference/01.functions/lsparsedatetime/_examples.md
- docs/03.reference/01.functions/ormexecutequery/_arguments/hql.md
- docs/03.reference/01.functions/ormexecutequery/_examples.md
- docs/03.reference/02.tags/documentsection/_examples.md
- docs/03.reference/02.tags/function/_attributes/modifier.md
- docs/03.reference/02.tags/logout/_examples.md
- docs/03.reference/02.tags/wddx/_examples.md
https://luceeserver.atlassian.net/browse/LDEV-1242
> Added a examples and modifier attribute to cffunction

- docs/03.reference/01.functions/fileopen/_examples.md
https://docs.lucee.org/reference/functions/fileopen.html
> add example how to access the resource type via fileOpen()

- docs/03.reference/01.functions/queryfilter/_examples.md
After a few years, the example (with hardcoded age) no longer worked :-)
https://docs.lucee.org/reference/functions/queryfilter.html
> Remove reference to age (< 21).

- docs/03.reference/02.tags/lock/tag.md
https://docs.lucee.org/reference/tags/lock.html
> cross ref cflock

- docs/03.reference/01.functions/argon2checkhash/_arguments/hash.md
- docs/03.reference/01.functions/argon2checkhash/_examples.md
- docs/03.reference/01.functions/generateargon2hash/_examples.md
https://docs.lucee.org/reference/functions/generateargon2hash.html
https://docs.lucee.org/reference/functions/argon2checkhash.html
> add argon2 exmaples

- docs/03.reference/01.functions/getcomponentstaticscope/function.md
- docs/03.reference/02.tags/component/tag.md
- docs/03.reference/02.tags/function/tag.md
- docs/03.reference/02.tags/static/tag.md
- docs/04.guides/04.cookbooks/28.StaticScope/page.md
- docs/04.guides/08.lucee-5/06.component-static/page.md
- docs/05.categories/275.static/category.md
https://docs.lucee.org/categories/static.html
> add static category

- api/data/FunctionPage.cfc
- api/data/TagPage.cfc
- api/reference/FunctionReferenceReader.cfc
- api/reference/TagReferenceReader.cfc
- builders/html/templates/function.cfm
- builders/html/templates/tag.cfm
https://luceeserver.atlassian.net/browse/LD-143
> LD-143 show required extension for functions and tags

- api/build/BuildProperties.cfc
- builders/html/Builder.cfc
> add search link for related test cases

- README.md
- docs/03.reference/01.functions/createobject/function.md
- docs/03.reference/02.tags/header/_attributes/charset.md
- docs/03.reference/02.tags/transaction/_attributes/isolation.md
- docs/03.reference/05.objects/string/parsedatetime/_arguments/format.md
- docs/04.guides/02.installing-lucee/02.windows/04.installing-oracle-java-on-windows/page.md
- docs/04.guides/02.installing-lucee/02.windows/11.starting-tomcat-and-verifying-the-installation-on-windows/page.md
- docs/04.guides/02.installing-lucee/20.installer-developers/page.md
- docs/04.guides/03.updating-lucee/02.migrate-from-railo/page.md
- docs/04.guides/06.extensions/12.extensions-couchdb/page.md
- docs/04.guides/13.Various/30.TIPS/02.TIPS-tricks/page.md
- docs/04.guides/13.Various/33.ubuntu-lucee-with-Tomcat7-multi-instance/page.md
- docs/06.docs/chapter.md
fix and update several broken links https://luceeserver.atlassian.net/browse/LD-132
> fix and update several broken links https://luceeserver.atlassian.net/browse/LD-132

- docs/03.reference/01.functions/imageresize/_arguments/blurFactor.md
https://luceeserver.atlassian.net/browse/LDEV-2102
> Updated a description to ImageResize() - blurFactor value 0-10 for LDEV-2102

- docs/03.reference/100.unsupported/chapter.md
Added query functions to unsupported list
> Added query functions to unsupported list

- docs/03.reference/01.functions/ispdfobject/_examples.md
- docs/03.reference/02.tags/document/_attributes/fontdirectory.md
- docs/04.guides/04.cookbooks/52.Flyingsaucer/page.md
- docs/04.guides/13.Various/23.lucee-maven/page.md
https://luceeserver.atlassian.net/browse/LDEV-2599
> Added a note to cfdocument fontDirectory

- docs/03.reference/01.functions/fileupload/_arguments/nameConflict.md
- docs/03.reference/02.tags/file/_attributes/nameconflict.md
https://luceeserver.atlassian.net/browse/LDEV-3122
> cffile nameconflict=forceunique for LDEV-3122

- docs/04.guides/05.working-with-source/01.build-from-source/page.md
Added text about purging dependency cache.
> Added build troubleshooting

- docs/03.reference/01.functions/round/function.md
https://dev.lucee.org/t/round-function/10157/2?u=andreas
> Enhance description of the round() function

- docs/03.reference/01.functions/clearTimeZone/_examples.md
- docs/03.reference/01.functions/clearTimeZone/function.md
> Delete docs/03.reference/01.functions/clearTimeZone directory

- docs/03.reference/02.tags/pdf/_attributes/action.md
https://luceeserver.atlassian.net/browse/LDEV-967
> Updated the cfpdf action=thumbnail as implemented LDEV-967

- docs/03.reference/01.functions/datetimeformat/_arguments/mask.md
- docs/03.reference/01.functions/isinstanceof/_examples.md
- docs/03.reference/01.functions/lsdatetimeformat/_arguments/mask.md
- docs/03.reference/01.functions/minute/_examples.md
- docs/03.reference/01.functions/parsedatetime/_arguments/format.md
- docs/03.reference/01.functions/restinitapplication/_examples.md
- docs/03.reference/02.tags/case/_examples.md
https://luceeserver.atlassian.net/browse/LDEV-3872
> Fixes LDEV-3872 (LSDateTimeFormat Mask) and Examples

- docs/03.reference/01.functions/rediscommandlowpriority/_arguments/async.md
- docs/03.reference/01.functions/transactionrollback/_arguments/savepoint.md
- docs/04.guides/13.Various/32.tutorial-lucee/04.tutorial-reporting-bugs/page.md
> Fix Markdown link and spelling

- docs/03.reference/05.objects/struct/append/_method.md
https://luceeserver.atlassian.net/browse/LD-147
> Added correction to struct.append() description for LD-147

- docs/03.reference/01.functions/cleartimezone/function.md
this PR restores cleartimezone function markdown file that has accidentaly been removed by my last PR. Don't know how this could have happend. 
https://github.com/lucee/lucee-docs/pull/1260
> restore cleartimezone function markdown file

- api/reference/FunctionReferenceReader.cfc
- api/reference/TagReferenceReader.cfc
- builders/html/templates/function.cfm
- builders/html/templates/tag.cfm
https://luceeserver.atlassian.net/browse/LD-151
> LD-151 show introduced date for argument and functions

- docs/03.reference/01.functions/fileappend/_examples.md
- docs/03.reference/01.functions/fileupload/function.md
- docs/03.reference/01.functions/fileuploadall/function.md
- docs/03.reference/02.tags/file/_attributes/action.md
- docs/03.reference/02.tags/file/_examples.md
- docs/04.guides/13.Various/49.file-upload-result/page.md
- docs/04.guides/13.Various/chapter.md
https://luceeserver.atlassian.net/browse/LD-150
> Added a page to describe the result of the file upload operation for LD-150

- api/data/Page.cfc
- builders/dash/templates/changelog.cfm
- builders/html/Builder.cfc
- builders/html/templates/changelog.cfm
- docs/03.reference/130.changelog/changelog.md
https://luceeserver.atlassian.net/browse/LD-154
> LD-154 add lucee changelog

- docs/04.guides/13.Various/50.locale-df-files/page.md
https://luceeserver.atlassian.net/browse/LD-156
> Added a docs for custom date and time for a locale using .df files for LD-156

- docs/04.guides/04.cookbooks/01.application-context-basic/page.md
- docs/04.guides/04.cookbooks/03.application-context-update/page.md
- docs/04.guides/04.cookbooks/16.caches-in-application-cfc/page.md
I have added a "description" to ensure that the page renders correctly.
> Ensure that Categories / Application / Guides renders correctly

- docs/03.reference/05.objects/array/shift/_examples.md
Code now runnable and comments correct
https://docs.lucee.org/reference/objects/array/shift.html
> Update _examples.md for array shift

- api/data/TagPage.cfc
https://luceeserver.atlassian.net/browse/LD-158
> Added a fix to show the description correctly in the cfscript docs for LD-158

- docs/04.guides/04.cookbooks/32.Startup_Listeners/page.md
https://docs.lucee.org/guides/cookbooks/Startup_Listeners.html
> improve startup listeners docs

- docs/04.guides/13.Various/01.system-properties/page.md
See https://dev.lucee.org/t/secure-ldap-docs-does-needs-updating/11324/2
> add env variable for ssl truststore

- docs/03.reference/02.tags/http/_usageNotes.md
https://luceeserver.atlassian.net/browse/LDEV-3545
https://luceeserver.atlassian.net/browse/LDEV-4264
> LDEV-3545 add usage notes for cfhttp multipart

- README.md
- docs/04.guides/02.installing-lucee/01.download-and-install/page.md
- docs/04.guides/02.installing-lucee/05.installation-linux/08.linux-install-ubuntu-commandbox/page.md
- docs/04.guides/05.working-with-source/01.build-from-source/page.md
- docs/04.guides/10.get-involved/09.contributing-contributors-agreement/page.md
- docs/04.guides/13.Various/32.tutorial-lucee/04.tutorial-reporting-bugs/page.md
Commandbox -> CommandBox
Github -> GitHub
Javascript -> JavaScript
> Fix word case

- docs/03.reference/01.functions/queryexecute/_examples.md
https://docs.lucee.org/reference/functions/queryexecute.html
> add a queryExecute insert and generatedkey exαmple

- docs/04.guides/02.installing-lucee/01.download-and-install/page.md
This PR gives detailed information about what snapshots, rc and stable releases are. This is due the latest community posts about having trouble and deciding what to choose.
> Add detailed information about the release names

- docs/04.guides/04.cookbooks/27.PreCompiled-Code/page.md
See some commentary in each commit message.
> revise the discussion of cfclasses, precompilation

- api/parsers/MarkdownParser.cfc
- api/rendering/TemplateRenderer.cfc
- builders/dash/templates/_method.cfm
- builders/dash/templates/_object.cfm
- builders/dash/templates/aToZIndex.cfm
- builders/dash/templates/category.cfm
- builders/dash/templates/changelog.cfm
- builders/dash/templates/function.cfm
- builders/dash/templates/implementationStatus.cfm
- builders/dash/templates/page.cfm
- builders/dash/templates/tag.cfm
- builders/html/helpers/sourceRepoLink.cfm
- builders/html/templates/_method.cfm
- builders/html/templates/_object.cfm
- builders/html/templates/aToZIndex.cfm
- builders/html/templates/category.cfm
- builders/html/templates/changelog.cfm
- builders/html/templates/function.cfm
- builders/html/templates/implementationStatus.cfm
- builders/html/templates/page.cfm
- builders/html/templates/tag.cfm
https://luceeserver.atlassian.net/browse/LD-163
> LD-162 avoid conflict with new markdownToHtml BIF

- docs/03.reference/100.unsupported/chapter.md
> decodeforhtml() was added at some point to Lucee

- docs/03.reference/01.functions/querytostruct/_examples.md
https://docs.lucee.org/reference/functions/querytostruct.html
> queryToStruct examples

- builders/html/assets/trycf/js/code-editor3.js
also change the engine selector to a radio, coz I'm too lazy for drop down selects
> add lucee 6 beta as a tryCF option

- docs/04.guides/13.Various/30.TIPS/14.TIPS-LDAP/page.md
Added the step how to get the LDAP server cert
> Update docs on LDAPS

- docs/04.guides/02.installing-lucee/01.download-and-install/page.md
formatting broken in https://docs.lucee.org/guides/installing-lucee/download-and-install.html
> broken formatting of HTML in markdown file

- docs/04.guides/13.Various/30.TIPS/01.TIPS-compile-code/page.md
Add info about cfml-compiler to compile page
> Update docs 

- builders/html/assets/css/base.37.min.css
- builders/html/assets/js/dist/base.37.min.js
https://luceeserver.atlassian.net/browse/LD-169
> Updated the missing bundles

- docs/04.guides/13.Various/01.system-properties/page.md
Fix download link in LUCEE_EXTENSIONS block
> Fix download link

- api/reference/FunctionReferenceReader.cfc
- api/reference/TagReferenceReader.cfc
- builders/cfdocs/Builder.cfc
https://luceeserver.atlassian.net/browse/LDEV-5501 
https://github.com/lucee/Lucee/pull/2553
> LDEV-5501 use name with case (requires lucee PR to work)

- api/parsers/MarkdownParser.cfc
- api/rendering/Pygments.cfc
- api/rendering/SyntaxHighlighter.cfc
- api/rendering/highlighter.py
- api/rendering/pygmentsCss.py
- builders/html/Builder.cfc
- builders/html/assets/css/highlight.css
https://luceeserver.atlassian.net/browse/LD-168
> LD-168 update to pygments 2.5.2

- docs/recipes/configuration.md
This link was added:
https://docs.lucee.org/recipes/maven.html
> Added link to "Using Maven" doc

- api/data/DocTree.cfc
> api: fix spelling

- docs/03.reference/01.functions/queryexecute/_examples.md
- docs/recipes/index.json
- docs/recipes/query-handling.md
https://dev.lucee.org/t/query-each-slow-lucee-6-2/15241/13
> Update QueryExecute() Examples
